config/routes.rb
Rails.application.routes.draw do
  get 'user/index'
  match 'user/serial'  => 'user#serial',:via => :post
  match 'user/serial_dev'  => 'user#serial_dev',:via => :post 
  post 'user' => 'user#button'

  resources :steps

end

app/models/step.rb
class Step < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/steps_controller.rb
class StepsController < ApplicationController
  before_action :set_step, only: [:show, :edit, :update, :destroy]

  # GET /steps
  # GET /steps.json
  def index
    @steps = Step.all
  end

  # GET /steps/1
  # GET /steps/1.json
  def show
  end

  # GET /steps/new
  def new
    @step = Step.new
  end

  # GET /steps/1/edit
  def edit
  end

  # POST /steps
  # POST /steps.json
  def create
    @step = Step.new(step_params)

    respond_to do |format|
      if @step.save
        format.html { redirect_to @step, notice: 'Step was successfully created.' }
        format.json { render :show, status: :created, location: @step }
      else
        format.html { render :new }
        format.json { render json: @step.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /steps/1
  # PATCH/PUT /steps/1.json
  def update
    respond_to do |format|
      if @step.update(step_params)
        format.html { redirect_to @step, notice: 'Step was successfully updated.' }
        format.json { render :show, status: :ok, location: @step }
      else
        format.html { render :edit }
        format.json { render json: @step.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /steps/1
  # DELETE /steps/1.json
  def destroy
    @step.destroy
    respond_to do |format|
      format.html { redirect_to steps_url, notice: 'Step was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_step
      @step = Step.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def step_params
      params.require(:step).permit(:name, :form)
    end
end

app/controllers/user_controller.rb
#require 'pi_piper'
require 'serialport'
class UserController < ApplicationController
  $button_msg = 'Hello'
  $serial_msg = 'Serial device is (or maybe) ready'
  $serial_dev = '/dev/cu.usbmodem14111'
  #$pin_led=PiPiper::Pin.new :pin => 4, :direction => :out
  def index
    @user = User.new
  end
  def button
    logger.info  "method button"
    if params[:name]=='on_button'
      logger.info 'On button pressed'
      $button_msg = 'On button pressed'
    elsif params[:name]=='off_button'
      #$pin_led.off
      logger.info 'Off button pressed'
      $button_msg = 'Off button pressed'
    end
    redirect_to '/user/index'
  end
  def serial
    sp = SerialPort.new($serial_dev, 9600, 8, 1, 0) # 9600bps, 8bit, stopbit 1, parity none
    logger.info  "method serial"
    @user = params[:user]
    print @user[:data]
    sp.puts @user[:data] # write
    $serial_msg= @user[:data] << " was sent."

    redirect_to '/user/index'
  end

  def serial_dev
    logger.info "Method serial_dev"
    @user = params[:user]
    $serial_dev = @user[:data]
    redirect_to '/user/index'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/steps_helper.rb
module StepsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MyApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/steps/_form.html.erb
<%= form_for(@step) do |f| %>
  <% if @step.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@step.errors.count, "error") %> prohibited this step from being saved:</h2>

      <ul>
      <% @step.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :form %><br>
    <%= f.text_field :form %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/steps/edit.html.erb
<h1>Editing Step</h1>

<%= render 'form' %>

<%= link_to 'Show', @step %> |
<%= link_to 'Back', steps_path %>

app/views/steps/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Steps</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Form</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @steps.each do |step| %>
      <tr>
        <td><%= step.name %></td>
        <td><%= step.form %></td>
        <td><%= link_to 'Show', step %></td>
        <td><%= link_to 'Edit', edit_step_path(step) %></td>
        <td><%= link_to 'Destroy', step, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Step', new_step_path %>

app/views/steps/new.html.erb
<h1>New Step</h1>

<%= render 'form' %>

<%= link_to 'Back', steps_path %>

app/views/steps/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @step.name %>
</p>

<p>
  <strong>Form:</strong>
  <%= @step.form %>
</p>

<%= link_to 'Edit', edit_step_path(@step) %> |
<%= link_to 'Back', steps_path %>

app/views/user/index.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Test rails app</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"><a href="#">Link <span class="sr-only">(current)</span></a></li>
        <li><a href="#">Link</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">One more separated link</a></li>
          </ul>
        </li>
      </ul>
      <form class="navbar-form navbar-left" role="search">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="#">Link</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

<div class = "container">

  <h1>Welcome to testapp</h1>
  <h2>About</h2>
  <p>This app will control raspberry-pi gpio output, serial, websocket, and more comming.</p>
  <br>

  <div class = "col-md-12">
    <div class="panel panel-default">
      <div class="panel-heading">Farmbot head controller</div>
      <div class="panel-body">
        <p>Lorem ipsum dolor sit amet, ius nostro detraxit cu, summo cotidieque eu sea. Sit assentior percipitur complectitur no, ad paulo tantas legere his, at est
          sonet explicari. Id sit error munere comprehensam. His in sonet epicurei.</p>
          <!-- <div class="alert alert-success" role="alert"><p></p></div> -->

          <div class = "col-md-6">
            <%= button_to "↓",{ :action => "button" ,:name => "on_button"},:class=>'btn btn-success'%>
            <%= button_to "↑",{ :action => "button" ,:name => "on_button"},:class=>'btn btn-success'%>
            <%= button_to "→",{ :action => "button" ,:name => "on_button"},:class=>'btn btn-success'%>
            <%= button_to "←",{ :action => "button" ,:name => "on_button"},:class=>'btn btn-success'%>
          </div>

          <div class = "col-md-6">
            aaa
          </div>

        </div>
      </div>
    </div>

    <div class = "col-md-6">
      <div class="panel panel-default">
        <div class="panel-heading">On-board LED controll</div>
        <div class="panel-body">
          <p>Onboard LED on/off can be controlled here. </p>
          <div class="alert alert-success" role="alert"><p><%= $button_msg %></p></div>
          <%= button_to "ON",{ :action => "button" ,:name => "on_button"},:class=>'btn btn-primary'%>
          <%= button_to "OFF",{ :action => "button" ,:name => "off_button"},:class=>'btn btn-primary'%>
        </div>
      </div>
    </div>

    <div class = "col-md-6">
      <div class="panel panel-default">
        <div class="panel-heading">Serial signal send form</div>
        <div class="panel-body">
          <p>Serial device connection and setting below. <p class ='text-danger'>Sending signal can cause bot's head to move.</p></p>
          <div class = "col-md-6">
            <div class="alert alert-success" role="alert"><p><%= $serial_msg %></p></div>
              <%= form_for(@user, :url => {:action => 'serial'}) do |f| %>
              <%= f.text_field  :data ,:class => "form-control"   %><br>
              <%= f.submit"Submit",:class => "btn btn-primary",:action=>'serial' %><br>
              <% end %>
          </div>
          <div class = "col-md-6">
            <div class="alert alert-warning" role="alert"><p>Serial device is set to '<%= $serial_dev %>'</p></div>
            <%= form_for(@user, :url => {:action => 'serial_dev'}) do |f| %>
            <%= f.text_field  :data ,:class => "form-control"   %><br>
            <%= f.submit"Submit",:class => "btn btn-warning",:action=>'serial_dev' %><br>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div><!-- container -->